BEGIN;
MERGE INTO public.dm_atividade da
USING
	(
		SELECT DISTINCT 
					ID_ATIVIDADE,
					COD_ATIVIDADE,
					ID_RESPONSAVEL,
					ID_SOLICITANTE,
					DESCRICAO,
					TIPO,
					DATA_INICIO,
					DATA_PREVISAO,
					DATA_FINALIZACAO,
					ATRASO
		from dblink('host=localhost user=postgres password=postgres dbname=lojabi',
		$$
			SELECT 	
					ID_ATIVIDADE,
					COD_ATIVIDADE,
					ID_RESPONSAVEL,
					ID_SOLICITANTE,
					DESCRICAO,
					TIPO,
					DATA_INICIO,
					DATA_PREVISAO,
					DATA_FINALIZACAO,
					ATRASO
		FROM atividade
		$$) AS atividade
					(ID_ATIVIDADE 		INT,
					COD_ATIVIDADE		VARCHAR,
					ID_RESPONSAVEL		INT,
					ID_SOLICITANTE		INT,
					DESCRICAO			VARCHAR,
					TIPO				CHAR(7),
					DATA_INICIO			TIMESTAMP,
					DATA_PREVISAO		TIMESTAMP,
					DATA_FINALIZACAO	TIMESTAMP,
					ATRASO				CHAR(3))
		ORDER BY 1
	) MERGE_SUBQUERY
ON (
		da.NK_ID_ATIVIDADE = MERGE_SUBQUERY.ID_ATIVIDADE
	)
WHEN NOT MATCHED THEN 

INSERT 
		(
			SK_ID_RESPONSAVEL,
			SK_ID_SOLICITANTE,
			NK_ID_ATIVIDADE,
			COD_ATIVIDADE,
			DESCRICAO,
			TIPO,
			DATA_INICIO,
			DATA_PREVISAO,
			DATA_FINALIZACAO,
			ATRASO
		)
VALUES 
		(
			MERGE_SUBQUERY.ID_RESPONSAVEL,
			MERGE_SUBQUERY.ID_SOLICITANTE,
			MERGE_SUBQUERY.ID_ATIVIDADE,
			MERGE_SUBQUERY.COD_ATIVIDADE,
			MERGE_SUBQUERY.DESCRICAO,
			MERGE_SUBQUERY.TIPO,
			MERGE_SUBQUERY.DATA_INICIO,
			MERGE_SUBQUERY.DATA_PREVISAO,
			MERGE_SUBQUERY.DATA_FINALIZACAO,
			MERGE_SUBQUERY.ATRASO
		)
WHEN MATCHED THEN 

UPDATE SET 
			SK_ID_RESPONSAVEL		=	MERGE_SUBQUERY.ID_RESPONSAVEL,
			SK_ID_SOLICITANTE		=	MERGE_SUBQUERY.ID_SOLICITANTE,
			NK_ID_ATIVIDADE			=	MERGE_SUBQUERY.ID_ATIVIDADE,
			COD_ATIVIDADE			=	MERGE_SUBQUERY.COD_ATIVIDADE,
			DESCRICAO				=	MERGE_SUBQUERY.DESCRICAO,
			TIPO					=	MERGE_SUBQUERY.TIPO,
			DATA_INICIO				=	MERGE_SUBQUERY.DATA_INICIO,
			DATA_PREVISAO			=	MERGE_SUBQUERY.DATA_PREVISAO,
			DATA_FINALIZACAO		=	MERGE_SUBQUERY.DATA_FINALIZACAO,
			ATRASO					=	MERGE_SUBQUERY.ATRASO,
			DADO_VERSAO				=	DADO_VERSAO + 1,
			DATA_ULTIMO_DADO		=	current_timestamp;
COMMIT;