BEGIN;
MERGE INTO public.ft_servico fts
USING
	(
		SELECT DISTINCT 
					ID_ATIVIDADE,
					ID_AVALIACAO,
					ID_LOJA,
					SETOR_SOLICITANTE
		from dblink('host=localhost user=postgres password=postgres dbname=lojabi',
		$$
			SELECT 	
					ID_ATIVIDADE,
					ID_AVALIACAO,
					ID_LOJA,
					SETOR_SOLICITANTE
		FROM servico
		$$) AS servico
					(ID_ATIVIDADE		INT,
					ID_AVALIACAO		INT,
					ID_LOJA				INT,
					SETOR_SOLICITANTE	VARCHAR)
		ORDER BY 1
	) MERGE_SUBQUERY
ON (
		fts.SK_ID_ATIVIDADE = MERGE_SUBQUERY.ID_ATIVIDADE
	)
WHEN NOT MATCHED THEN 

INSERT 
		(
			SK_ID_ATIVIDADE,
			SK_ID_AVALIACAO,
			SK_ID_LOJA,
			SETOR_SOLICITANTE
		)
VALUES 
		(
			MERGE_SUBQUERY.ID_ATIVIDADE,
			MERGE_SUBQUERY.ID_AVALIACAO,
			MERGE_SUBQUERY.ID_LOJA,
			MERGE_SUBQUERY.SETOR_SOLICITANTE
		)
WHEN MATCHED THEN 

UPDATE SET 
			SK_ID_ATIVIDADE			=	MERGE_SUBQUERY.ID_ATIVIDADE,
			SK_ID_AVALIACAO			=	MERGE_SUBQUERY.ID_AVALIACAO,
			SK_ID_LOJA				=	MERGE_SUBQUERY.ID_LOJA,
			SETOR_SOLICITANTE		=	MERGE_SUBQUERY.SETOR_SOLICITANTE,
			DADO_VERSAO				=	DADO_VERSAO + 1,
			DATA_ULTIMO_DADO		=	current_timestamp;
COMMIT;